In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('Restaurant_Reviews.tsv', delimiter='\t',quoting=3)

In [3]:
#cleaning the dataset
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\SHWETA\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [4]:
corpus = []
for i in range(0, 1000):
    zomato_ratings = re.sub('[^a-zA-Z]',' ',dataset['Review'][i])
    zomato_ratings = zomato_ratings.lower()
    zomato_ratings = zomato_ratings.split()
    ps = PorterStemmer()
    all_stopwords= stopwords.words('english')
    all_stopwords.remove('not')
    zomato_ratings = [ps.stem(word) for word in zomato_ratings if not word in set(all_stopwords)]
    zomato_ratings = ' '.join(zomato_ratings)
    corpus.append(zomato_ratings)

In [28]:
print(corpus)

['wow love place', 'crust not good', 'not tasti textur nasti', 'stop late may bank holiday rick steve recommend love', 'select menu great price', 'get angri want damn pho', 'honeslti tast fresh', 'potato like rubber could tell made ahead time kept warmer', 'fri great', 'great touch', 'servic prompt', 'would not go back', 'cashier care ever say still end wayyy overpr', 'tri cape cod ravoli chicken cranberri mmmm', 'disgust pretti sure human hair', 'shock sign indic cash', 'highli recommend', 'waitress littl slow servic', 'place not worth time let alon vega', 'not like', 'burritto blah', 'food not amaz', 'servic also cute', 'could care less interior beauti', 'perform', 'right red velvet cake ohhh stuff good', 'never brought salad ask', 'hole wall great mexican street taco friendli staff', 'took hour get food tabl restaur food luke warm sever run around like total overwhelm', 'worst salmon sashimi', 'also combo like burger fri beer decent deal', 'like final blow', 'found place accid could

In [7]:
# Import necessary libraries
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
import pandas as pd

# Assuming 'dataset' is already loaded and contains 'Review' and 'Rating' columns
# Handle missing values (if any)
dataset = dataset.dropna(subset=['Review', 'zomato_ratings'])

# Convert ratings into sentiment labels (0: Negative, 1: Positive, 2: Neutral)
def classify_sentiment(rating):
    if rating >= 4:
        return 1  # Positive
    elif rating == 3:
        return 2  # Neutral
    else:
        return 0  # Negative

dataset['Sentiment'] = dataset['zomato_ratings'].apply(classify_sentiment)

# Extract reviews and labels
corpus = dataset['Review'].astype(str).tolist()  # Convert reviews to string to avoid issues
y = dataset['Sentiment'].values  # Labels (0,1,2)

# Convert text to feature vectors
cv = CountVectorizer(max_features=1500)
X = cv.fit_transform(corpus).toarray()  # Convert text data to numerical vectors

# Ensure dataset labels and vectorized features match
if len(X) != len(y):
    print(f"Warning: Mismatch in features ({len(X)}) and labels ({len(y)})!")

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=0)

# Train the model (Change to Logistic Regression if needed)
classifier = MultinomialNB()
classifier.fit(X_train, y_train)

print("Model training completed successfully!")

KeyError: ['zomato_ratings']

In [30]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.20, random_state = 0)

In [31]:
#training Naive Bayes

from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression(multi_class='multinomial', solver='lbfgs')
classifier.fit(X_train, y_train)

MultinomialNB()

In [9]:
#Prediction on the test set
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_est),1)),1))
unique_labels = set(y_pred)
print(f"Predicted Sentiments: {unique_labels}") 

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 0]
 [0 1]
 [0 0]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [1 0]
 [0 1]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [0 1]
 [1 1]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 1]
 [1 1]
 [1 1]

In [32]:
# making Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[75 22]
 [22 81]]


0.78

In [33]:
import joblib

# Save the trained classifier model
joblib.dump(classifier, 'Zomato_review_analysis.pkl')

# Save the CountVectorizer
joblib.dump(cv, 'vectorizer.pkl')

['vectorizer.pkl']

In [34]:
print(classifier)

MultinomialNB()


In [35]:
import joblib

# Load the saved vectorizer
cv = joblib.load("vectorizer.pkl")

# Load the trained model
classifier = joblib.load("Zomato_review_analysis.pkl")

# Test if vectorizer is working
sample_text = ["This food is absolutely delicious!"]
vectorized_text = cv.transform(sample_text).toarray()
print(vectorized_text)  # It should print a numerical array

[[0 0 0 ... 0 0 0]]


In [36]:
print(classifier)

MultinomialNB()


In [37]:
print(hasattr(classifier, "var_"))

False


In [38]:
print(X_train.dtype) 

int64


In [39]:
print(np.any(np.isnan(X_train))) 

False


In [40]:
print(np.any(np.isinf(X_train)))

False


In [41]:
print(hasattr(classifier, "class_prior_")) 

False


In [42]:
print(hasattr(classifier, "var_"))

False


In [43]:
print(X_train.shape)

(800, 1500)


In [44]:
import numpy as np

print("X_train shape:", X_train.shape)  # Should have (samples, features)
print("y_train shape:", y_train.shape)  # Should match x_train
print("Unique classes in y_train:", np.unique(y_train))  # Should have multiple classes
print("Any NaN in x_train:", np.any(np.isnan(X_train)))  # Should be False
print("Any NaN in y_train:", np.any(np.isnan(y_train)))  # Should be False

X_train shape: (800, 1500)
y_train shape: (800,)
Unique classes in y_train: [0 1]
Any NaN in x_train: False
Any NaN in y_train: False


In [45]:
def predict_review(review):
    review_vectorized = cv.transform([review]).toarray()  
    prediction = classifier.predict(review_vectorized)[0]  
    return "Positive" if prediction == 1 else "Negative"

# Example prediction
print(predict_review("The food was great!"))

Positive
